"""add default to finaly of credit of credit migration

Revision ID: 5428d614ee25
Revises: ff77d383cac3
Create Date: 2023-12-14 01:59:47.333888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5428d614ee25'
down_revision: Union[str, None] = 'ff77d383cac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
