"""add default to finaly of credit of credit migration

Revision ID: 9222356490ac
Revises: a6dd663d0f0f
Create Date: 2023-12-14 09:30:28.801928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9222356490ac'
down_revision: Union[str, None] = 'a6dd663d0f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
