"""First migration

Revision ID: 9fc0bdd99838
Revises: 
Create Date: 2023-12-13 23:39:59.195537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fc0bdd99838'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('mounth_payment', sa.Integer(), nullable=True))
    op.alter_column('credit', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('credit', 'data_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('credit', 'total_sum',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('credit', 'remainder_sum',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_transaction', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_transaction', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('remittance_transaction', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('remittance_transaction', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payment_transaction', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payment_transaction', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credit', 'remainder_sum',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credit', 'total_sum',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('credit', 'data_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('credit', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('credit', 'mounth_payment')
    # ### end Alembic commands ###
